const elements = {
  year: document.querySelector(".year"),
  showTitle: document.querySelector(".title"),
  imageDiv: document.querySelector(".top-image-container"),
  navBar: document.querySelector(".nav-bar"),
  redLine: document.querySelector(".text-underline-long"),
  pageTitle: document.querySelector(".curr-page-title"),
  selfPortrait: document.querySelector(".flip-card-inner"),
  textLinks: document.querySelectorAll("#text-link"),
  show: document.querySelectorAll(".appear"),
  divs: document.querySelectorAll(".empty-div"),
  content: document.querySelector(".content"), 
  form: document.querySelector(".my-form"),
  status: document.querySelector(".my-form-status"),
};
